# Generated by Django 4.2.7 on 2026-03-04 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='auth_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='auth_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='auto_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='detected_at_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='detected_from_file',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='path_parameters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='query_parameters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='request_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='response_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProjectUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_method', models.CharField(choices=[('zip', 'Zip File'), ('github', 'GitHub URL')], max_length=20)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('extracting', 'Extracting Files'), ('scanning', 'Security Scanning'), ('analyzing', 'AI Analysis'), ('extracting_endpoints', 'Extracting Endpoints'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=30)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_message', models.TextField(blank=True)),
                ('detected_language', models.CharField(blank=True, max_length=50)),
                ('detected_framework', models.CharField(blank=True, max_length=50)),
                ('endpoints_found', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('temp_directory', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
