# Generated by Django 4.2.7 on 2026-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_endpoint_auth_required_endpoint_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='code_samples',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
