# Generated by Django 4.2.7 on 2026-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_endpoint_code_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupload',
            name='upload_method',
            field=models.CharField(choices=[('files', 'Multiple Files'), ('zip', 'Zip File'), ('github', 'GitHub URL')], max_length=20),
        ),
    ]
