# Generated by Django 4.2.7 on 2026-03-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectupload_upload_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturenode',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='architecturenode',
            name='ai_generation_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='architecturenode',
            name='created_by_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectupload'),
        ),
        migrations.AddField(
            model_name='architecturenode',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectupload',
            name='architecture_analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectupload',
            name='architecture_nodes_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectupload',
            name='generate_architecture',
            field=models.BooleanField(default=False),
        ),
    ]
