# Generated by Django 4.2.7 on 2026-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_architecturenode_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='ast_confidence_score',
            field=models.FloatField(blank=True, help_text='Confidence in AST security classification (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='ast_reasoning',
            field=models.TextField(blank=True, help_text='AST analysis reasoning'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='ast_security_level',
            field=models.CharField(blank=True, help_text='AST-detected security level', max_length=50),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='detected_decorators',
            field=models.JSONField(blank=True, default=list, help_text='Security decorators detected by AST'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='security_features',
            field=models.JSONField(blank=True, default=list, help_text='Security features detected by AST'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='user_security_override',
            field=models.CharField(blank=True, help_text="User's manual security level override", max_length=50),
        ),
    ]
