# Generated by Django 4.2.7 on 2026-03-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_ast_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_base_url',
            field=models.URLField(blank=True, help_text='Base URL for live API testing, e.g. https://myapi.com'),
        ),
    ]
